server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.SQLServerDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:sqlserver://teamwater.database.windows.net:1433;database=db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: teamwater
    password: P@SSWORD123
  h2:
    console.enabled: true